version: '3.9'

services:
  voltup:
    container_name: "voltup"
    image: voltup:latest
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      RABBIT_HOST: rabbit
      OPENAPIKEY:

    networks:
      default:
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    networks:
      default:

networks:
  default:
    internal: true


