spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    port: 5672
    username: rabbitmq
    password: rabbitmq

  application:
    name: app
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

  flyway:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    locations: db/migration/
    enabled: false
    baseline-on-migrate: true
  ai:
    openai:
      api-key: ${OPENAPIKEY}

api:
  security:
    secret: sa-secret



management:
  endpoints:
    web:
      exposure:
        include: health, info, openapi, swagger-ui

  endpoint:
    health:
      show-details: always
    info:
      git:
        enabled: true
        mode: full

springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui
    enabled: true
  api-docs:
    enabled: true